### ISSUE TITLE
splitting up managed_serviceaccount plugin to support more granular RBAC configuration 

### ISSUE THREAD

**Issue by TheRealHaoLiu** [stolostron/ocmplus.cm#57]
in our current implementation managed_serviceaccount plugin create the maanged serviceaccount and create a manifestwork to configure clusterrolebinding to bind cluster-admin clusterrole to the created maanged service account

in our next iteration we would like to split up the plugin into 2 different ones 

1. to create managedserviceaccount and fetch managed serviceaccount token 
2. to create role and rolebinding to bind to the managed serviceaccount

**Comment by TheRealHaoLiu** [comment]
example playbook tasks
```
  - name: "Get managed ServiceAccount token for {{ hostvars[inventory_hostname].cluster_name }}"
    ocmplus.cm.managed_serviceaccount_addon:
      hub_kubeconfig: "{{ lookup('env', 'K8S_AUTH_KUBECONFIG') }}"
      managed_cluster: "{{ hostvars[inventory_hostname].cluster_name }}"
      wait: True
      timeout: 60
    register: managed_serviceaccount
  - name: "Get configure RBAC for {{ hostvars[inventory_hostname].cluster_name }}"
    ocmplus.cm.managed_serviceaccount_rbac_addon:
      hub_kubeconfig: "{{ lookup('env', 'K8S_AUTH_KUBECONFIG') }}"
      managed_cluster: "{{ hostvars[inventory_hostname].cluster_name }}"
      cluster_scoped: True
      managed_serviceaccount: managed_serviceaccount
      role_template: "/path/to/template"
      wait: True
      timeout: 60
```
managed_serviceaccount_addon plugin will create the managed_serviceaccount, like before, the ouput will now include the name and namespace of the manged_serviceaccount and name and namespace of the serviceaccount that get created 
example output in json:
```
{
  "name": "name of the ManagedServiceAccount resource",
  "namespace": "namespace of the ManagedServiceAccount resource",
  "service_account":
    "name": "name of the ServiceAccount on managed cluster",
    "namespace": "namespace of the ServiceAccount on managed cluster"
    "token": "token of the ServiceAccount"
}
```
this output will be use for the new managed_serviceaccount_rbac_addon

example input of the new plugin 
```
      hub_kubeconfig: "{{ lookup('env', 'K8S_AUTH_KUBECONFIG') }}"
      managed_cluster: "{{ hostvars[inventory_hostname].cluster_name }}"
      managed_serviceaccount: managed_serviceaccount
      role_template: "/path/to/template"
      wait: True
      timeout: 60
```

role_template will be a reference to a clusterrole or role file 
if its a clusterrole than we create the clusterrole and clusterrolebinding 
if its a role than we create the role and rolebinding in managed_serviceaccount.serviceaccount.namespace

**Comment by TheRealHaoLiu** [comment]
open question: should we just extend managed_serviceaccount_addon to add paramater to specify RBAC information 
or should we add a new role to configure RBAC

**Comment by TheRealHaoLiu** [comment]
for first iteration of design we will focus on applying clusterrole and in the future we will think about how to implement roles

**Comment by TheRealHaoLiu** [comment]
question for @hanqiuzh 
how AAP friendly is    `role_template: "/path/to/template"`

**Comment by nathanweatherly** [comment]
move role_template to rbac_template
add erandom string to both role and rolebinding created
add ownerref to manifestwork (owned by managedserviceaccount)
add cleanup step by deleting MSA resource at end of playbook with UID

**Comment by tphee** [comment]
Sample playbook:

```

- name: "Creating configmap {{ configmap_name }} on {{ target_hosts }} host group"
  hosts: "{{ target_hosts }}"
  connection: local
  tasks:
  - name: "Get ClusterProxy URL for {{ hostvars[inventory_hostname].cluster_name }}"
    ocmplus.cm.cluster_proxy_addon:
      hub_kubeconfig: "{{ hostvars['local-cluster'].kubeconfig }}"
      managed_cluster: "{{ hostvars[inventory_hostname].cluster_name }}"
      wait: True
      timeout: 60
    register: cluster_proxy_url
  - name: debug
    debug:
      msg: "{{ cluster_proxy_url.cluster_url }}"

  - name: "Get managed ServiceAccount token for {{ hostvars[inventory_hostname].cluster_name }}"
    ocmplus.cm.managed_serviceaccount_addon:
      hub_kubeconfig: "{{ hostvars['local-cluster'].kubeconfig }}"
      managed_cluster: "{{ hostvars[inventory_hostname].cluster_name }}"
      wait: True
      timeout: 60
    register: managed_serviceaccount
  - name: debug
    debug:
      msg: "managed_serviceaccount name: {{ managed_serviceaccount.managed_serviceaccount.name }}"

  - name: "Configure ServiceAccount RBAC for {{ hostvars[inventory_hostname].cluster_name }}"
    ocmplus.cm.managed_serviceaccount_rbac_addon:
      hub_kubeconfig: "{{ hostvars['local-cluster'].kubeconfig }}"
      managed_cluster: "{{ hostvars[inventory_hostname].cluster_name }}"
      managed_serviceaccount: "{{ managed_serviceaccount }}"
      rbac_template: /tmp/role2.yaml
      wait: True
      timeout: 60
    register: token
  - name: debug
    debug:
      msg: "token length: {{ token.token | length }}"

  - name: "Creating configmap {{ configmap_name }} on {{ hostvars[inventory_hostname].cluster_name }}"
    kubernetes.core.k8s:
      state: present
      host: "{{ cluster_proxy_url.cluster_url }}"
      validate_certs: no
      api_key: "{{token.token}}"
      definition:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: "{{ configmap_name }}"
          namespace: "{{ configmap_namespace }}"
    ignore_errors: true

  - name: "Removing ServiceAccount {{ managed_serviceaccount.managed_serviceaccount.name }} for {{ hostvars[inventory_hostname].cluster_name }}"
    kubernetes.core.k8s:
      kubeconfig: "{{ hostvars['local-cluster'].kubeconfig }}"
      state: absent
      definition:
        apiVersion: "{{ managed_serviceaccount.managed_serviceaccount.api_version }}"
        kind: "{{ managed_serviceaccount.managed_serviceaccount.kind }}"
        metadata:
          name: "{{ managed_serviceaccount.managed_serviceaccount.name }}"
          namespace: "{{ managed_serviceaccount.managed_serviceaccount.namespace }}"
      wait: true
      wait_timeout: 600
```

**Comment by tphee** [comment]
RBAC Role sample:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: managed-serviceaccount-role
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - create
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: managed-serviceaccount-rolebinding
  namespace: default
roleRef:
  apiGroup: ""
  kind: Role
  name: managed-serviceaccount-role
```

RBAC ClusterRole sample:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-proxy
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
```
